### ISSUE TITLE
Mediascanner fails

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#1515]
### Expected behaviour
When starting media scanner together with CasparCG, scanning of the media folders should be done.

### Current behaviour
Media scanner throws a lot of errors. The media scanner don't start when using the bat script, have to start it manually.

----

* Commit: casparcg-server-528389a9ffb27157eacbedc2ecbc7a29446349ea-windows
* Server version: master
* Operating system: Windows 11

---

**_Error messages from Media scanner:_**
{"level":50,"time":1703683232449,"pid":20176,"hostname":"DSGNCG01","name":"scanner","err":{"type":"PouchError","message":"Invalid rev format","stack":"Error\n    at new CustomPouchError (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:656:21)\n    at createError (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:665:10)\n    at parseRevisionInfo (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:4438:12)\n    at parseDoc (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:4488:17)\n    at C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:5264:20\n    at Array.map (<anonymous>)\n    at C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:5260:29\n    at tryCode (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:5070:11)\n    at runWriteOperation (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:5133:5)\n    at executeNext (C:\\snapshot\\media-scanner\\node_modules\\pouchdb-node\\lib\\index.js:5082:7)","status":400,"name":"bad_request","error":true,"docId":"CHL/MOVIES/40_FF_MAPS_UK"},"msg":"Invalid rev format"}

**Comment by 5opr4ni** [comment]
TLS works!
